spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n" # 控制台中日志的输出格式
#  file:
#    path: C:/Users/fancyyyy/Desktop/sellDataFile # 配置日志文件的输出路径，文件名默认为spring.logging
#    name: C:/Users/fancyyyy/Desktop/sellDataFile/sell.log # 配置日志文件的输出路径的文件名
#  level:
#    com.fancy.sell.LoggerTest: debug # 设置日志的输出级别

wechat:
  mpAppId: wxfb9e3debd2a6ef71
  mpAppSecret: b420a5255611d7f2993e29b990bf98a6
  mchid:
  mchkey:
  keyPath:
  notifyUrl:
